import GamesPage from "../../components/GamesPage"
export const metadata = {
    title: 'Games',
    description: 'Generated by create next app',
}

export default function Page() {
    return (
        <>
            <GamesPage />
        </>
    )
}

export const runtime = "edge"